### ISSUE TITLE
Separate functionality of SVA into two modules

### ISSUE THREAD

**Issue by bpaniagua** [DCBIA-OrthoLab/ShapeVariationAnalyzer#27]
We should separate the PCA calculation / mean calculation etc and shape learning/classification into two different modules / CLIs

@vicory @juanprietob Mateo Lopez

**Comment by juanprietob** [comment]
PCA calculation is already a sperate module. The mean is calculated when the population exploration is done.  The learning/classification is not included in the CLI yet. 
Could you give us more details on what the feature you want?

**Comment by bpaniagua** [comment]
@juanprietob Maybe in our next meeting today, you can do another live demo. I downloaded the extension and was not able to figure out the structure. I will try again this morning so we can re convey later.

**Comment by bpaniagua** [comment]
Clarified. Closing.
