### ISSUE TITLE
Extension has problems with python dependencies

### ISSUE THREAD

**Issue by bpaniagua** [DCBIA-OrthoLab/ShapeVariationAnalyzer#28]
Hi @lopezmt @juanprietob 

I installed manually sklearn and scipy for the SVA extension downloaded from the extension manager in Ubuntu 16.04. The extension fails to install some python libraries. 

Here is the message:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/bpaniagua/.config/NA-MIC/Extensions-27534/ShapeVariationAnalyzer/lib/Slicer-4.11/qt-scripted-modules/ShapeVariationAnalyzer.py", line 24, in <module>
    import shapepcalib as shapca

Could you please look into that?
Thanks,
Bea

**Comment by juanprietob** [comment]
This commit solves the issue of including the library shapepca 
https://github.com/DCBIA-OrthoLab/ShapeVariationAnalyzer/commit/004014a10b6ce5eca25c4490a4ec4320fdcaffb8

**Comment by bpaniagua** [comment]
Thank you for this quick fix. The module now works and loads. There is a remaining error message when Slicer starts:
"RuntimeError: qSlicerScriptedLoadableModule::setPythonSource - Failed to load scripted loadable module: class shapepcalib was not found in file /home/bpaniagua/.config/NA-MIC/Extensions-27539/ShapeVariationAnalyzer/lib/Slicer-4.11/qt-scripted-modules/shapepcalib.py"

Here is how I try to use SVA:

1. Download latest Slicer nightly (in this case the one compiled on 11-11-2018)
2. Manually install sklearn and scipy via ./Slicer --launch bin/python-real -m pip install scikit-learn
That command works (Successfully installed scikit-learn-0.20.0 scipy-1.1.0)

**Comment by lopezmt** [comment]
The issue is solved, I have created a pull request to apply the
modifications.

Le lun. 12 nov. 2018 à 16:44, Beatriz Paniagua <notifications@github.com> a
écrit :

**Comment by bpaniagua** [comment]
@lopezmt :+1: will try asap
