### ISSUE TITLE
Suggested changes in layout behavior for PCA tab

### ISSUE THREAD

**Issue by bpaniagua** [DCBIA-OrthoLab/ShapeVariationAnalyzer#30]
When the button "process and export csv" is pressed in the PCA tab, the layout of slicer automatically changes to "four-up quantitative" and it should be "standard quantitative" so the 3D view can be seen.

**Comment by lopezmt** [comment]
The module was just setting a layout with a plot view In the next pull request, the default layout is now 'standard quantitative'.

**Comment by bpaniagua** [comment]
Fantastic! I will try asap.
