### ISSUE TITLE
Re-fork repositories to avoid confusion

### ISSUE THREAD

**Issue by jcfr** [DCBIA-OrthoLab/ShapeVariationAnalyzer#45]
@pdedumast To avoid confusion, could you delete your project `pdedumast/ShapeVariationAnalyzer` and re-fork the one hosted in the `DCBIA-OrthoLab` organization. See https://github.com/DCBIA-OrthoLab/ShapeVariationAnalyzer

The fork graph currently shows this:

![image](https://user-images.githubusercontent.com/219043/70098491-11a11c80-15fa-11ea-9874-4018873b4a24.png)

@ClementMirabel, @ninatubau, @juanprietob (for NIRALUser) : After @pdedumast is done, you may have to do the same.

Thanks :pray:

**Comment by pdedumast** [comment]
Done! :thumbsup:
![image](https://user-images.githubusercontent.com/19345763/70120417-d2f87a00-166c-11ea-9c2b-047b939e2890.png)

**Comment by jcfr** [comment]
Thanks :+1:
