### ISSUE TITLE
Change wiki to point to this repo

### ISSUE THREAD

**Issue by JEHoctor** [DCBIA-OrthoLab/ShapeVariationAnalyzer#47]
Currently points to https://github.com/pdedumast/ShapeVariationAnalyzer.

**Comment by jcfr** [comment]
Which wiki page reference the wrong repository ?

**Comment by JEHoctor** [comment]
[This page.](https://www.slicer.org/wiki/Documentation/Nightly/Modules/ShapeVariationAnalyzer) Ctrl-f for "The source code of this module is available on GitHub". It's at the very bottom.

**Comment by jcfr** [comment]
Closing. Fixed in https://www.slicer.org/w/index.php?title=Documentation%2FNightly%2FModules%2FShapeVariationAnalyzer&type=revision&diff=63347&oldid=60656
